language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
sudo: required
addons:
  apt:
    packages:
    - wine1.6
script:
- npm run react_build
- npm run dist:test
true:
  branch: master
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
  - build/AtomPlayer-win.exe
  skip_cleanup: true
  on:
    repo: RgtArRr/AtomPlayer
