language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
sudo: required
addons:
  apt:
    packages:
    - wine1.6
script:
- npm run react_build
- npm run dist
true:
  branch: master
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
  - build/atomplayer-linux-x64.zip
  - build/atomplayer-win32-x64.zip
  - build/atomplayer-mac-x64.zip
  skip_cleanup: true
  on:
    tags: true
    repo: RgtArRr/AtomPlayer
