language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run react_build
true:
  branch: master
deploy:
  provider: releases
  api_key:
    secure: XOR/AxrTtHnBPNCKPmAw34vfBs2+11GCWUt7mSpI2Wp5ZiL9TQ3tLjB4sPFJaHRakS3N+F2DakdsKEcMFp8FECUt08QN+XBSylE99PjwX9m+NL8gaBLUfjLabtgfyJCnJX084xgOx8TG2x4QjHUGWmS3RC6UAcRjtqHSso1llvF0pq4IIo9FcVrBpM/AvRT5nZao6ewa5Yq4f1bqaDfTbtM2iYHFX86HZcfo3blznAUE+Y5FbNZ0WrgkSkZLAWz6iSCVEm5xIgZZ/6DGjRPBYaA8qi7/r5N318GY+62FGRiUIPGlS6+Wsqnb3bmRAua1wN+ll8ZCu+n13vGSt1n1e/8DBPtgSkGkbX5ej9wWJ08QqJ2+YSshuzKBb+oy1cu4K/HRUpoqrzrlpyQXm3KcqysAvTO9IoirwGVbONuO+eytZgyno4XcO2hpAxErcBOaGkaAGL/s0rXOt2XX2PGkPVHTzCCaHCPhkjmQmPrYDSKDEwhT29AnST7lHkByMAfOmwncO0v5gXwn2PcBhEGtMf3fzC/EjrqL/lupHmqQEF0B7h1Wydhr40MKXDwlqbouTUDyu10eASCpRpwDr8OTwH3oqMQ7PlDrOyPxo0xe3gkUCJfpl/GqJWztBYFPtXAoLSPv4PRVkalnF4b2r5k4eX5TqwhFQ9UjZtuhi+uBnJ0=
  file: resources/js/app.min.js
  on:
    repo: RgtArRr/AtomPlayer
